using UnityEngine;
using UnityEngine.UI;
using TMPro;

/// <summary>
/// Exibe a UI do Ultimate no Canvas (HUD).
/// Mostra a barra de progresso visual de recarga, o countdown numérico (ex: 15.4s) e o atalho [U].
/// Suporta tanto referências manuais do Inspector quanto criação automática no Canvas.
/// </summary>
public class UltimateUI : MonoBehaviour
{
    [Header("Referências Globais")]
    public PlayerUltimate ultimateScript;

    [Header("Componentes Manuais de UI (Opcional)")]
    [Tooltip("Arraste uma Imagem com Image Type = Filled para fazer a barra/círculo de recarga.")]
    public Image cooldownFillImage;
    
    [Tooltip("Texto numérico do Countdown (ex: 14.5s ou PRONTO [U]).")]
    public TextMeshProUGUI countdownText;

    [Tooltip("Ícone ou fundo do painel do Ultimate.")]
    public Image statusBorderImage;

    [Header("Configurações da UI Automática (HUD)")]
    public bool useAutoGeneratedUI = true;
    public Vector2 screenPosition = new Vector2(-280f, 40f); // Deslocado para a esquerda para não sobrepor orbs
    public Vector2 panelSize = new Vector2(220f, 65f);

    [Header("Cores dos Estados")]
    public Color readyColor = new Color(0.2f, 1.0f, 0.4f, 1.0f);    // Verde Brilhante
    public Color cooldownColor = new Color(1.0f, 0.3f, 0.2f, 1.0f); // Vermelho / Laranja
    public Color activeColor = new Color(1.0f, 0.85f, 0.2f, 1.0f);  // Dourado

    private GameObject autoCanvasObj;
    private Image autoFillImage;
    private TextMeshProUGUI autoText;
    private Image autoBorderImage;

    void Start()
    {
        if (ultimateScript == null)
        {
            ultimateScript = GetComponentInParent<PlayerUltimate>() ?? GetComponent<PlayerUltimate>();
        }

        // Se o usuário não arrastou componentes manuais no Inspector e habilitou auto-geração, cria o Canvas HUD
        if ((cooldownFillImage == null || countdownText == null) && useAutoGeneratedUI)
        {
            BuildAutoGeneratedCanvas();
        }
    }

    void Update()
    {
        if (ultimateScript == null) return;

        float progress = ultimateScript.GetCooldownProgress(); // 0 a 1
        float remainingSec = ultimateScript.GetCooldownRemaining();
        bool isReady = ultimateScript.IsUltimateReady();
        bool isActive = ultimateScript.IsUltimateActive();

        // 1. Atualizar Preenchimento da Barra / Círculo de Cooldown (Fill Amount)
        Image targetFill = cooldownFillImage != null ? cooldownFillImage : autoFillImage;
        if (targetFill != null)
        {
            targetFill.fillAmount = progress;

            if (isActive) targetFill.color = activeColor;
            else if (isReady) targetFill.color = readyColor;
            else targetFill.color = cooldownColor;
        }

        // 2. Atualizar Texto do Countdown
        TextMeshProUGUI targetText = countdownText != null ? countdownText : autoText;
        if (targetText != null)
        {
            if (isActive)
            {
                targetText.text = "<color=#FFD700>[ ULT ATIVA ]</color>";
            }
            else if (isReady)
            {
                targetText.text = "<color=#00FF66>[ ULT PRONTA ]\n<size=80%>[ Pressione U ]</size></color>";
            }
            else
            {
                targetText.text = $"<color=#FF5555>{remainingSec:F1}s</color>";
            }
        }

        // 3. Atualizar Borda / Brilho do painel
        Image targetBorder = statusBorderImage != null ? statusBorderImage : autoBorderImage;
        if (targetBorder != null)
        {
            if (isReady)
            {
                // Leve efeito de pulso de luz quando pronto
                float pulse = 0.8f + Mathf.PingPong(Time.time * 2.5f, 0.2f);
                targetBorder.color = readyColor * pulse;
            }
            else if (isActive)
            {
                targetBorder.color = activeColor;
            }
            else
            {
                targetBorder.color = new Color(0.2f, 0.2f, 0.2f, 0.8f);
            }
        }
    }

    private void BuildAutoGeneratedCanvas()
    {
        // 1. Criar Canvas Overlay no HUD
        autoCanvasObj = new GameObject("Ultimate_CanvasHUD");
        Canvas canvas = autoCanvasObj.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        canvas.sortingOrder = 95;

        CanvasScaler scaler = autoCanvasObj.AddComponent<CanvasScaler>();
        scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
        scaler.referenceResolution = new Vector2(1920, 1080);

        autoCanvasObj.AddComponent<GraphicRaycaster>();

        // 2. Criar Painel Principal (Ancorado no Canto Inferior Direito por padrão)
        GameObject panelObj = new GameObject("UltimatePanel");
        panelObj.transform.SetParent(autoCanvasObj.transform, false);

        RectTransform panelRect = panelObj.AddComponent<RectTransform>();
        panelRect.anchorMin = new Vector2(1, 0); // Canto inferior direito
        panelRect.anchorMax = new Vector2(1, 0);
        panelRect.pivot = new Vector2(1, 0);
        panelRect.anchoredPosition = screenPosition;
        panelRect.sizeDelta = panelSize;

        // Fundo do Painel
        autoBorderImage = panelObj.AddComponent<Image>();
        autoBorderImage.color = new Color(0.1f, 0.1f, 0.1f, 0.85f);

        // 3. Criar Barra de Progresso / Fill Image
        GameObject fillObj = new GameObject("CooldownBarFill");
        fillObj.transform.SetParent(panelObj.transform, false);

        RectTransform fillRect = fillObj.AddComponent<RectTransform>();
        fillRect.anchorMin = Vector2.zero;
        fillRect.anchorMax = Vector2.one;
        fillRect.offsetMin = new Vector2(4, 4);
        fillRect.offsetMax = new Vector2(-4, -4);

        autoFillImage = fillObj.AddComponent<Image>();
        autoFillImage.type = Image.Type.Filled;
        autoFillImage.fillMethod = Image.FillMethod.Horizontal;
        autoFillImage.fillOrigin = (int)Image.OriginHorizontal.Left;
        autoFillImage.color = readyColor;

        // 4. Criar Texto Numérico do Countdown (TMPro)
        GameObject textObj = new GameObject("CountdownText");
        textObj.transform.SetParent(panelObj.transform, false);

        RectTransform textRect = textObj.AddComponent<RectTransform>();
        textRect.anchorMin = Vector2.zero;
        textRect.anchorMax = Vector2.one;
        textRect.offsetMin = Vector2.zero;
        textRect.offsetMax = Vector2.zero;

        autoText = textObj.AddComponent<TextMeshProUGUI>();
        autoText.fontSize = 20f;
        autoText.alignment = TextAlignmentOptions.Center;
        autoText.fontStyle = FontStyles.Bold;
        autoText.color = Color.white;
        
        // Tentar carregar fonte padrão do projeto
        TMP_FontAsset font = Resources.Load<TMP_FontAsset>("Fonts & Materials/LiberationSans SDF");
        if (font != null) autoText.font = font;
    }
}
